openapi: 3.0.0
info:
  title: maps
  version: '1.0'
  contact:
    email: test@dev.com
  description: 地図API
servers:
  - url: 'http://localhost:8080'
paths:
  /api/maps/deg2name:
    get:
      summary: ''
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  name:
                    type: string
                    description: 12方位名
              examples:
                example:
                  value:
                    status: true
                    name: 'N'
      operationId: get-api-maps-deg2name
      description: 方位の角度を12方位名に変換
      parameters:
        - schema:
            type: number
            minimum: 0
            maximum: 360
            format: float
          in: query
          name: deg
          required: true
          description: 方位の角度
    parameters: []
  /api/maps/tky2jgdg:
    get:
      summary: ''
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  lat:
                    type: number
                    description: 十進緯度（世界測地系）
                  lon:
                    type: number
                    description: 十進経度（世界測地系）
              examples:
                example:
                  value:
                    status: true
                    lat: 35.68078249
                    lon: 139.767235
      operationId: get-api-maps-tky2jgdg
      description: 日本測地系を世界測地系に変換（1次式）
      parameters:
        - schema:
            type: number
            format: double
          in: query
          name: lat
          required: true
          description: 十進緯度（日本測地系）
        - schema:
            type: number
            format: double
          in: query
          name: lon
          required: true
          description: 十進経度（日本測地系）
    parameters: []
  /api/maps/jgd2tkyg:
    get:
      summary: ''
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  lat:
                    type: number
                    description: 十進緯度（日本測地系）
                  lon:
                    type: number
                    description: 十進経度（日本測地系）
              examples:
                example:
                  value:
                    status: true
                    lat: 35.67755556
                    lon: 139.7704444
      operationId: get-api-maps-jgd2tkyg
      description: 世界測地系を日本測地系に変換（1次式）
      parameters:
        - schema:
            type: number
            format: double
          in: query
          name: lat
          required: true
          description: 十進緯度（世界測地系）
        - schema:
            type: number
            format: double
          in: query
          name: lon
          required: true
          description: 十進経度（世界測地系）
    parameters: []
  /api/maps/distancet:
    get:
      summary: '２地点間の距離（球面三角法）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  distance:
                    type: number
                    description: 距離（cm）
              examples:
                example:
                  value:
                    status: true
                    distance: 27335.473262593438
      operationId: get-api-maps-distancet
      description: ２地点間の距離（球面三角法）
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat1
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon1
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 35.447495
          in: query
          name: lat2
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.6424
          in: query
          name: lon2
          required: true
          description: 十進経度（世界測地系[GSR80]）
    parameters: []
  /api/maps/distanceh:
    get:
      summary: '２地点間の距離（ヒュベニ）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  distance:
                    type: number
                    description: 距離（cm）
              examples:
                example:
                  value:
                    status: true
                    distance: 27248.24567995688
      operationId: get-api-maps-distanceh
      description: ２地点間の距離（ヒュベニ）
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat1
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon1
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 35.447495
          in: query
          name: lat2
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.6424
          in: query
          name: lon2
          required: true
          description: 十進経度（世界測地系[GSR80]）
    parameters: []
  /api/maps/distances:
    get:
      summary: '２地点間の距離（測地線航海算法）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  distance:
                    type: number
                    description: 距離（cm）
              examples:
                example:
                  value:
                    status: true
                    distance: 32204.322252668517
      operationId: get-api-maps-distances
      description: ２地点間の距離（測地線航海算法）
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat1
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon1
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 35.447495
          in: query
          name: lat2
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.6424
          in: query
          name: lon2
          required: true
          description: 十進経度（世界測地系[GSR80]）
    parameters: []
tags:
  - name: maps
    description: ''
components:
  schemas: {}
  securitySchemes: {}
